denv/imovie/imovie/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/',include('account.urls')),
    url('social-auth/',
		include('social.apps.django_app.urls', 
        namespace='social')),
    url(r'^movie/',include('movie.urls',
        namespace='movies')),
    url(r'^comment/',include('comment.urls',
        namespace='comments')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)

denv/imovie/movie/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [

	url(r'^movie-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.movie_detail, 
		name='movie_detail'),
	url(r'^movie-list/$', views.movie_list, name='movie_list'),

	url(r'^activity-list/$', views.activity_list, name='activity_list'),
	url(r'^activity-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.activity_detail, 
		name='activity_detail'),
	
	url(r'^like/$', views.movie_like, 
		name='movie_like'),	
	url(r'^movie-comment/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.movie_comment, 
		name='movie_comment'),
	url(r'^movie-ranking/$', views.movie_ranking, name='movie_ranking'),
	url(r'^(?P<category_slug>[-\w]+)/$', views.movie_list, 
		name='movie_list_by_category'),

]

denv/imovie/movie/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from embed_video.fields import EmbedVideoField

# Create your models here.
class Category(models.Model):

	name = models.CharField(max_length=200,
							db_index=True)
	slug = models.SlugField(max_length=200,
							db_index=True,
							unique=True)

	class Meta:
		ordering = ('name',)
		verbose_name = 'category'
		verbose_name_plural = 'categories'

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('movies:movie_list_by_category',
						args=[self.slug])

class Movie(models.Model):

	category = models.ForeignKey(Category,
								related_name='movies')
	name = models.CharField(max_length=200)
	slug = models.SlugField(max_length=200,blank=True)
	director = models.CharField(max_length=200)
	scriptwriter = models.CharField(max_length=200)
	nation = models.CharField(max_length=100)
	star = models.CharField(max_length=200)
	length = models.CharField(max_length=100)

	year = models.DecimalField(max_digits=19,decimal_places=0)
	language = models.CharField(max_length=200,blank=True, null=True)

	description = models.TextField(blank=True)
	poster = models.ImageField(upload_to='movies/%Y/%m/%d',blank=True)
	rank = models.DecimalField(max_digits=10, decimal_places=2)



	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)

	users_like = models.ManyToManyField(User,
									related_name='movies_liked',
									blank=True) 
	video = EmbedVideoField(default="")

	class Meta:
		ordering = ('name',)
		index_together = (('id', 'slug'),)

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('movies:movie_detail',
						args=[self.id,self.slug])

	def get_comment_url(self):
		return reverse('movies:movie_comment',
						args=[self.id,self.slug])


class Activity(models.Model):

	title = models.CharField(max_length=200)
	slug = models.SlugField(max_length=200)
	body = models.TextField()
	active = models.BooleanField(default=True)
	created = models.DateTimeField(auto_now_add=True)
	date = models.DateField(blank=True, null=True)
	todate = models.DateField(blank=True,null=True)

	class Meta:
		ordering = ('created',)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('movies:activity_detail',
						args=[self.id,self.slug])

denv/imovie/movie/forms.py
from django import forms


class SearchForm(forms.Form):
	query = forms.CharField()

denv/imovie/movie/views.py
from django.shortcuts import render, get_object_or_404
from .models import Movie, Category, Activity
from django.views.decorators.http import require_GET, require_POST
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from account.models import User
from comment.forms import ShortCommentForm, CommentForm
from django.http import HttpResponse, JsonResponse
from comment.models import ShortComment
from django.db.models import Avg, Sum

from .forms import SearchForm
from haystack.query import SearchQuerySet
from ajaxDecorators.decorators import ajax_required
import redis
from django.conf import settings

from django.views.decorators.cache import cache_page
from django.views.decorators.csrf import csrf_protect

#from django.utils.safestring import mark_safe
#import markdown
# Create your views here.

r = redis.StrictRedis(host=settings.REDIS_HOST,
					port=settings.REDIS_PORT,
					db=settings.REDIS_DB)

@cache_page(60*15)
@csrf_protect
def movie_list(request, category_slug=None):
	category = None
	categories = Category.objects.all()
	movies = Movie.objects.all()
	if category_slug:
		category = get_object_or_404(Category, slug=category_slug)
		movies = movies.filter(category=category)
	else:
		movies = Movie.objects.all()

	paginator = Paginator(movies, 8)
	page = request.GET.get('page')
	try:
		movies = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer deliver the first page
		movies = paginator.page(1)
	except EmptyPage:
		if request.is_ajax():
			# If the request is AJAX and the page is out of range return an empty page
			return HttpResponse('')
			# If page is out of range deliver last page of results
			movies = paginator.page(paginator.num_pages)
		if request.is_ajax():
			return render(request,
					'movies/movie/list_ajax.html',
					{'section': 'movies', 
					'movies': movies})

	form = SearchForm()
	if 'query' in request.GET:
		form = SearchForm(request.GET)
		if form.is_valid():
			cd = form.cleaned_data
			results = SearchQuerySet().models(Movie).filter(content=cd['query']).load_all()
			# count total results
			total_results = results.count()
		return render(request, 'movies/movie/list.html',
								{'form': form,
								'cd': cd,
								'results': results,
								'total_results': total_results})

	return render(request,
				'movies/movie/list.html',
				{'section': 'movies',
				'movies': movies,
				'form': form,
				'category':category,
				'categories':categories})

@cache_page(60*15)
@csrf_protect
def movie_detail(request, id, slug):
	movie = get_object_or_404(Movie,
							id=id,
							slug=slug)

	total_views = r.incr('movie:{}:views'.format(movie.id))
	r.zincrby('movie_ranking',movie.id,1)

	#add shortcomment 
	author = request.user
	shortcomments = movie.shortcomments.filter(active=True)
	comments = movie.comments.filter(active=True)

	new_shortcomment =None
	if request.method=="POST":
		shortcomment_form = ShortCommentForm(data=request.POST)	
		if shortcomment_form.is_valid():
			new_shortcomment = shortcomment_form.save(commit=False)
			new_shortcomment.movie = movie
			new_shortcomment.author = author 
			new_shortcomment.save()
	else:
		shortcomment_form = ShortCommentForm()

	#rank
	if shortcomments.exists():
		rank = ShortComment.objects.filter(movie_id=id).aggregate(avg_ranking=Avg('rank'))
		movie.rank = rank['avg_ranking']			
	else:
		rank = movie.rank
	movie.save()

	return render(request,
					'movies/movie/detail.html',
					{'movie':movie,
					'author':author,
					'section': 'movies',
					'shortcomments':shortcomments,
					'comments':comments,
					'new_shortcomment':new_shortcomment,
					'shortcomment_form':shortcomment_form,
					'total_views':total_views})

@login_required
@cache_page(60*15)
@csrf_protect
def movie_comment(request,id,slug):
	movie = get_object_or_404(Movie,
						id=id,
						slug=slug)
	
	author = request.user
	new_comment =None
	if request.method=="POST":
		comment_form = CommentForm(data=request.POST)	
		if comment_form.is_valid():
			new_comment = comment_form.save(commit=False)
			new_comment.movie = movie
			new_comment.author = author 
			new_comment.save()
	else:
		comment_form = CommentForm()

	return render(request,
				'movies/movie/review.html',
				{'author':author,
				'movie':movie,
				'new_comment':new_comment,
				'comment_form':comment_form})
	
@login_required
@require_POST
@ajax_required
def movie_like(request):
	movie_id = request.POST.get('id')
	action =request.POST.get('action')
	if movie_id and action:
		try:
			movie = Movie.objects.get(id=movie_id)
			if action == 'like':
				movie.users_like.add(request.user)
			else:
				movie.users_like.remove(request.user)
			return JsonResponse({'status':'ok'})
		except:
			pass
	return JsonResponse({'status':'ko'})


def movie_ranking(request):
	
	movie_ranking = r.zrange('movie_ranking',0,-1,desc=True)[:6]
	movie_ranking_ids = [int(id) for id in movie_ranking]
	movie_viewed = list(Movie.objects.filter(id__in=movie_ranking_ids))
	movie_viewed.sort(key=lambda x: movie_ranking_ids.index(x.id))
	movies = movie_viewed

	movies_by_rank = Movie.objects.order_by('-rank')[:6]

	return render(request,
				"movies/movie/movie_ranking.html",
				{"movie_viewed":movie_viewed,
				"movies":movies,
				"movies_by_rank":movies_by_rank})

def activity_list(request):
	activities = Activity.objects.all()

	return render(request,
				"activity/activity_list.html",
				{"activities":activities})


def activity_detail(request,id,slug):
	activity = get_object_or_404(Activity,
								id=id,
								slug=slug)

	return render(request,
				"activity/activity_detail.html",
				{"activity":activity})

denv/imovie/movie/templates/movies/movie/detail.html
{% extends "base.html" %}
{% load thumbnail %}
{% load embed_video_tags %}

{% block title %}{{ movie.name }}{% endblock %}

{% block content %}
	<div class="content">
	<div class="movie_top">
		<div class="col-md-9 movie_box">
			<div class="grid images_3_of_2">
				<div class="movie_image">
					<span class="movie_rating">{{ movie.rank|floatformat:2 }}</span>
					{% thumbnail movie.poster "400" as im %}
					<img src="{{ im.url }}" class="img-responsive" alt=""/>
					{% endthumbnail %}
				</div>
				<div class="movie_rate">
					<div class="rating_desc"><p>Your Vote :</p></div>
					<form action="" class="sky-form">
					<fieldset>					
					<section>
						<div class="rating">
							<input type="radio" name="stars-rating" id="stars-rating-5">
							<label for="stars-rating-5"><i class="icon-star"></i></label>
							<input type="radio" name="stars-rating" id="stars-rating-4">
							<label for="stars-rating-4"><i class="icon-star"></i></label>
							<input type="radio" name="stars-rating" id="stars-rating-3">
							<label for="stars-rating-3"><i class="icon-star"></i></label>
							<input type="radio" name="stars-rating" id="stars-rating-2">
							<label for="stars-rating-2"><i class="icon-star"></i></label>
							<input type="radio" name="stars-rating" id="stars-rating-1">
							<label for="stars-rating-1"><i class="icon-star"></i></label>
						</div>
					</section>
					</fieldset>
					</form>
					<div class="clearfix"> </div>
				</div>
				<div class="title"><a href= "{{ movie.get_comment_url }}" >write a review</a></div>
			</div>
			<div class="col-md-3" style="float: right;">
			{% with total_likes=movie.users_like.count users_like=movie.users_like.all %}
				<div id="user_movie_like" >
						<a href="#" data-id="{{ movie.id }}" data-action="{% if request.user in users_like %}un{% endif %}like" class="like button">
							{% if request.user not in users_like %}
								Like
							{% else %}
								Unlike
							{% endif %}
						</a>
				</div>
			{% endwith %}
			</div>

			<div class="desc1 span_3_of_2">
				<p class="movie_option"><strong>Country: </strong><a href="#">{{ movie.nation }}</a></p>
				<p class="movie_option"><strong>Year: </strong>{{movie.year}}</p>
				<p class="movie_option"><strong>Category: </strong><a href="#">{{ movie.category }}</a></p>
				<p class="movie_option"><strong>Director: </strong>{{ movie.director }}</p>
				<p class="movie_option"><strong>Scriptwriter: </strong>{{ movie.scriptwriter }}</p>
				<p class="movie_option"><strong>Actors: </strong>{{movie.star}}</p>
				<p class="movie_option"><strong>Language: </strong>{{movie.language}}</p>
				<p class="movie_option"><strong>Length: </strong>{{movie.length}}</p>

				{% with total_likes=movie.users_like.count users_like=movie.users_like.all %}
				<ul class="single_list">
					<li><i class="icon5"></i>
				<span class="count">
					<span class="total">
				<p>{{ total_likes }}</p></li></span></span>
				</ul>
				{% endwith %}
				<p class="movie_option"><strong>View:</strong> {{ total_views }}</p></li>
			</div>
			
			<div class="clearfix"> </div>
			<p class="m_4">{{movie.description}}</p>
			
			<div id="trailer">
			{% video movie.video as my_video %}
				{% video my_video 'small' %}
			{% endvideo %}
			</div>
			<br>

			<h3>Add a new shortcomment</h3>
			<form id="shortcomment_form" action="." method="post">
				<div class="to">
				<input type="number" class="text" value="Rank" name="rank" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Rank';}">
				</div>

				<div class="text">
					<textarea type="text" value="Comment:" name="body" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Comment:';}">Comment:</textarea>
				</div>
				{% csrf_token %}
				<div class="form-submit1">
				   <input name="submit" type="submit" id="submit" value="Submit Your Message"><br>
				</div>
			</form>

			<div class="single">
			{% with shortcomments.count as total_shortcomments %}
				<h1>
					{{ total_shortcomments }} shortcomment{{ total_shortcomments|pluralize }}
				</h1>
			{% endwith %}
			</div>
			<ul class="single_list">
				{% for shortcomment in shortcomments %}	
				<li>
					<div class="preview"><a href="#">
						{% thumbnail shortcomment.get_author_url.profile.photo "30" as im %}
						<img class="img-circle" src="{{ im.url }}" class="img-responsive" alt=""></a>
						{% endthumbnail %}
					</div>
					<div class="data">
						<div class="title"><a href="{{ shortcomment.get_author_url.profile.get_absolute_url }}" id="author">{{ shortcomment.author }}</a>  /  {{ shortcomment.created.month }} {{ shortcomment.created.day }}, {{ shortcomment.created.year }}  /  {{shortcomment.rank|floatformat:1 }} <a href="#">reply</a></div>
						<p>{{ shortcomment.body}}</p>
					</div>
					<div class="clearfix"></div>
				</li>
				{% empty %}
					<p>There are no shortcomments yet.</p>
				{% endfor %}
			</ul>
		</div>			  
		<div class="clearfix"> </div>
	</div>
	</div>
</div>		
{% endblock %}


{% block domready %}
	$('a.like').click(function(e){
		e.preventDefault();
		$.post('{% url "movies:movie_like" %}',
			{
				id: $(this).data('id'),
				action: $(this).data('action')
			},
			function(data){
				if (data['status'] == 'ok')
				{
					var previous_action = $('a.like').data('action');

					// toggle data-action
					$('a.like').data('action', previous_action == 'like' ? 'unlike' : 'like');
					// toggle link text
					$('a.like').text(previous_action == 'like' ? 'Unlike' : 'Like');

					// update total likes
					var previous_likes = parseInt($('span.count .total').text());
					$('span.count .total').text(previous_action == 'like' ? previous_likes + 1 : previous_likes - 1);
				}
		});
	});
{% endblock %}

denv/imovie/movie/templates/movies/movie/list.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}Movie list{% endblock %}


{% block content %}
<div class="content">
	<div class="box_1">
		<h1 class="m_2">Categories</h1>
		<div class="search">	
			<form action="." method="get" id="SearchForm">
			<input type="text" value="Search..." name="query" onFocus="this.value='';" onBlur="if (this.value == '') {this.value ='';}">
			<input type="submit" value="Search">
			</form>
		</div>
		<div id="sidebar" style="width: 100%;float: left ;">
			<ul class="list-group">
				 {% if not category %} {% endif %}
					<a href="{% url "movies:movie_list" %}"><strong>All</strong></a>&nbsp;&nbsp;		
				{% for c in categories %}
				{% if category.slug == c.slug %} {% endif %}
					<a href="{{ c.get_absolute_url }}"><strong>{{ c.name }}</strong></a>&nbsp;&nbsp;
				{% endfor %}
			</ul>	
		</div>
	</div>

	<div class="box_2">
		<div class="col-md-12 grid_3">
			<div id="movie-list" >
				{% if "query" in request.GET %}
				<h3>Found {{ total_results }} result{{ total_results|pluralize }}</h3>
				{% for result in results %}
				{% with movie=result.object %}
				<div class="col-md-2 grid_2">
					<a href="{{ movie.get_absolute_url }}" class="hvr-shutter-out-horizontal">
					{% thumbnail movie.poster "240x310" crop="100%" as im %}
						<img src="{{ im.url }}" class="img-responsive" alt=""/>
					{% endthumbnail %}
					</a>
				</div>
				{% endwith %}
				{% empty %}
				<p>There are no results.</p>
				{% endfor %}
				{% else %}
					{% include "movies/movie/list_ajax.html" %}
				{% endif %}
			</div>
		</div>
	</div>
	<div class="clearfix"> </div>
</div>
</div>
{% endblock %}


{% block domready%}
	var page = 1;
	var empty_page = false;
	var block_request = false;

	$(window).scroll(function() {
		var margin = $(document).height() - $(window).height() - 200;
		if ($(window).scrollTop() > margin && empty_page == false && block_request == false) {
			block_request = true;
			page += 1;
			$.get('?page=' + page, function(data) {
				if(data == '')
				{
					empty_page = true;
				}
				else {
					block_request = false;
					$('#movi-list').append(data);
				}
			});
		}
	});
{% endblock%}

denv/imovie/movie/templates/movies/movie/list_ajax.html
{% load thumbnail %}

{% for movie in movies %}
	<div class="col-md-2 grid_2">
	<a href="{{ movie.get_absolute_url }}" class="hvr-shutter-out-horizontal">
		{% thumbnail movie.poster "240x310" crop="100%" as im %}
			<img src="{{ im.url }}" class="img-responsive" alt=""/>
		{% endthumbnail %}
	</a>
	</div>
{% endfor %}

denv/imovie/movie/templates/movies/movie/movie_ranking.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}Movie list{% endblock %}


{% block content %}
<div class="content">
	<div class="box_2">
		<h1 class="m_2">Ranking by views</h1>
		<div class="col-md-12 grid_3">
			<div id="movie-list" >
				{% for movie in movies %}
					<div class="col-md-2 grid_2">
					<a href="{{ movie.get_absolute_url }}" class="hvr-shutter-out-horizontal">
						{% thumbnail movie.poster "240x310" crop="100%" as im %}
							<img src="{{ im.url }}" class="img-responsive" alt=""/>
						{% endthumbnail %}
					</a>
					</div>
				{% endfor %}
			</div>
		</div>
		<div><br><br><h1>&nbsp;&nbsp;</h1></div>
		<h1 class="m_2">Ranking by ranks</h1>
		<div class="col-md-12 grid_3">
			<div id="movie-list" >
				{% for movie in movies_by_rank %}
				<div class="col-md-2 grid_2">
				<a href="{{ movie.get_absolute_url }}" class="hvr-shutter-out-horizontal">
					{% thumbnail movie.poster "240x310" crop="100%" as im %}
						<img src="{{ im.url }}" class="img-responsive" alt=""/>
				{% endthumbnail %}
				</a>
				</div>
				{% endfor %}
			</div>
		</div>
	<div class="clearfix"> </div>
</div>
</div>
</div>
{% endblock %}

denv/imovie/movie/templates/movies/movie/review.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}{{ movie.name }}{% endblock %}

{% block content %}
<div class="content">
	{% if new_comment %}
		<h1 class="m_2">Your review has been added.</h1><br><br><br>
	{% else %}
	<h1 class="m_2" style="margin-left:3%">Add a new review</h1><br><br><br>
	<div>
		<form id="comment_form" action="." method="post">
			<div class="to">
			<input type="text" class="text" value="title" name="title" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'title';}" style="margin-left:3%">
			</div>
			<div class="review">
			    <textarea type="review" value="Review:" name="body" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Review:';}" style="margin-left:3%">Review:</textarea>
			</div>
			{% csrf_token %}
			<div class="form-submit1" style="margin-left:3%">
			   <input name="submit" type="submit" id="submit" value="Submit Your Review"><br>
			</div>
		</form>
	</div>
	{% endif %}
</div>
</div>
{% endblock %}

denv/imovie/movie/templates/movies/movie/top_movie_list.html
{% load thumbnail %}

<div class="slider">
	<div class="callbacks_container">
		<ul class="rslides" id="slider">
			{% for top_movie in top_movies%}
			<li>
				{% thumbnail top_movie.poster "1140x457" crop="45%" as im %}
					<img src="{{ im.url }}" class="img-responsive" alt=""/>
				{% endthumbnail %}
				<div class="button">
					<a href="{{ top_movie.get_absolute_url }}" class="hvr-shutter-out-horizontal">View</a>
				</div>
			</li>			
			{% endfor %}
		</ul>
	</div>
</div>

denv/imovie/movie/templates/movies/movie/user_movie_like_list_ajax.html
{% load thumbnail %}

<h1>My movie</h1>
{% for movie in movies %}
<span style="float: left;width: 30%;">
	<div class ="movie-list">
		<a href="{{ movie.get_absolute_url }}">
			{% thumbnail movie.poster "100" as im %}
				<img src="{{ im.url }}">
			{% endthumbnail %}
		</a>
		<div class="info">
			<a href="{{ movie.get_absolute_url }}" class="name">{{ movie.name }}</a>
		</div>
	</div>
</span>>
{% endfor %}