denv/imovie/account/urls.py
from django.conf.urls import url
from . import views

from django.contrib.auth.views import login
from django.contrib.auth.views import logout
from django.contrib.auth.views import logout_then_login
from django.contrib.auth.views import password_change
from django.contrib.auth.views import password_change_done
from django.contrib.auth.views import password_reset
from django.contrib.auth.views import password_reset_done
from django.contrib.auth.views import password_reset_confirm
from django.contrib.auth.views import password_reset_complete


urlpatterns = [
		
	#login logout
	url(r'^login/$', views.login_and_register, name='login'),
	url(r'^logout/$', logout, name='logout'),
	url(r'^logout-then-login/$', logout_then_login, name='logout_then_login'),
	
	#change password
	url(r'^password-change/$', password_change, 
		{'template_name': 'registration/password_form.html'}, 
		name='password_change'),
	url(r'^password-change/done/$', password_change_done, 
		{'template_name': 'registration/password_change_done.html'},
		name='password_change_done'),
	
	#reset password
	#restore password urls
	url(r'^password-reset/$',password_reset,
		name='password_reset'),
	url(r'^password-reset/done/$',password_reset_done,
		name='password_reset_done'),
	url(r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$',
		password_reset_confirm,
		name='password_reset_confirm'),
	url(r'^password-reset/complete/$',
		password_reset_complete,
	name='password_reset_complete'),

	#view your dashborad
	url(r'^dashboard/$', views.dashboard, name='dashboard'),
	url(r'^$', views.home, name='home'),

	#edit profile
	url(r'^edit/$', views.edit, name='edit'),

	url(r'^user-detail/(?P<username>[-\w]+)/$', views.user_detail, name='user_detail'),

	#url(r'^users/(?P<username>[-\w]+)/$',
		#views.user_detail,
		#name='user_detail'),

	#url(r'^users/follow/$', views.user_follow, name='user_follow'),


]

denv/imovie/comment/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [

	url(r'^movie-detail/(?P<id>\d+)/$', views.comment_detail, 
		name='comment_detail'),
	url(r'^review-list/$', views.comment_list, name='comment_list'),
]

denv/imovie/imovie/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/',include('account.urls')),
    url('social-auth/',
		include('social.apps.django_app.urls', 
        namespace='social')),
    url(r'^movie/',include('movie.urls',
        namespace='movies')),
    url(r'^comment/',include('comment.urls',
        namespace='comments')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)

denv/imovie/movie/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [

	url(r'^movie-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.movie_detail, 
		name='movie_detail'),
	url(r'^movie-list/$', views.movie_list, name='movie_list'),

	url(r'^activity-list/$', views.activity_list, name='activity_list'),
	url(r'^activity-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.activity_detail, 
		name='activity_detail'),
	
	url(r'^like/$', views.movie_like, 
		name='movie_like'),	
	url(r'^movie-comment/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.movie_comment, 
		name='movie_comment'),
	url(r'^movie-ranking/$', views.movie_ranking, name='movie_ranking'),
	url(r'^(?P<category_slug>[-\w]+)/$', views.movie_list, 
		name='movie_list_by_category'),

]

denv/imovie/account/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

# Create your models here.
class Profile(models.Model):
	user = models.OneToOneField(settings.AUTH_USER_MODEL)
	date_of_birth = models.DateField(blank=True, null=True)
	photo = models.ImageField(upload_to='users/%Y/%m/%d', blank=True)
	
	def __str__(self):
		return 'Profile for user {}'.format(self.user.username)

	def get_absolute_url(self):
		user = self.user
		return reverse('user_detail',
				args=[user.username])

denv/imovie/account/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile


class LoginForm(forms.Form):
	username = forms.CharField()
	password = forms.CharField(widget=forms.PasswordInput)

class UserRegistrationForm(forms.ModelForm):
	password = forms.CharField(label='Password',
								widget =forms.PasswordInput)
	password2 = forms.CharField(label = 'Repeat password',
								widget =forms.PasswordInput)

	class Meta:
		model = User
		fields = ('username','first_name','last_name','email')

	def clean_password2(self):
		cd = self.cleaned_data
		if cd['password'] != cd['password2']:
			raise forms.ValidationError('Password don\'t match.')
		return cd['password2']

class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('date_of_birth', 'photo')

denv/imovie/account/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import authenticate, login
from .forms import LoginForm, UserRegistrationForm, UserEditForm, ProfileEditForm
from django.contrib.auth.decorators import login_required

from django.contrib.auth.models import User
from .models import Profile

from django.contrib import messages

from account.models import User
from movie.models import Movie
from comment.models import ShortComment, Comment

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from movie.forms import SearchForm
from haystack.query import SearchQuerySet

import redis
from django.conf import settings

from django.views.decorators.cache import cache_page
from django.views.decorators.csrf import csrf_protect

#from decimal import Decimal

@cache_page(60*15)
@csrf_protect
def login_and_register(request):
	if request.method == 'POST':
		form = LoginForm(request.POST)
		if form.is_valid():
			cd = form.cleaned_data
			user = authenticate(username=cd['username'],
								password=cd['password'])
		if user is not None:
			if user.is_active:
				login(request, user)
				return HttpResponseRedirect('/account/')
			else:
				messages.error(request,'Disabled account')
		else:
			messages.error(request,'Invalid login')
			#return render(request,'registration/login.html',{'error_info': '密码错误'})
			#return HttpResponse('触发ajax')
	else:
		form = LoginForm()

	if request.method =='POST':
		user_form = UserRegistrationForm(request.POST)
		if user_form.is_valid():
			#Create a new user object but avoid saving it yet
			new_user = user_form.save(commit=False)
			#Set the chosen password
			new_user.set_password(user_form.cleaned_data['password'])
			#Save the User object
			new_user.save()
			#Create the user profile
			profile = Profile.objects.create(user=new_user)
			#add action stream
			#create_action(new_user, 'has created an account')
			return render(request,
						'account/login_and_register.html',
						{'new_user':new_user})
	else:
		user_form = UserRegistrationForm()
	return render(request, 
				'account/login_and_register.html', 
				{'form': form,
				'user_form':user_form})


@login_required
def dashboard(request):

	author = request.user.id
	#shortcomment list
	shortcomments = ShortComment.objects.filter(author_id=author)
	comments = Comment.objects.filter(author_id=author)
	#my movie list
	movies = Movie.objects.filter(users_like=author)

	paginator = Paginator(shortcomments,8)
	page = request.GET.get('page')
	try:
		shortcomments = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer deliver the first page
		shortcomments = paginator.page(1)
	except EmptyPage:
		if request.is_ajax():
			# If the request is AJAX and the page is out of range return an empty page
			return HttpResponse('')
			# If page is out of range deliver last page of results
			shortcomments = paginator.page(paginator.num_pages)
		if request.is_ajax():
			return render(request,
					'account/dashboard.html',
					{'section': 'dashboard', 
					'shortcomments': shortcomments})

	return render(request,
				'account/dashboard.html',
				{'section': 'dashboard',
				'shortcomments':shortcomments,
				'comments':comments,
				'movies':movies})
	

@login_required
def edit(request):
	if request.method == 'POST':
		user_form = UserEditForm(instance=request.user,
								 data=request.POST)
		profile_form = ProfileEditForm(instance=request.user.profile,
									   data=request.POST,
									   files=request.FILES)
		if user_form.is_valid() and profile_form.is_valid():
			user_form.save()
			profile_form.save()
			messages.success(request, 'Profile updated successfully')
		else:
			messages.error(request, 'Error updating your profile')
	else:
		user_form = UserEditForm(instance=request.user)
		profile_form = ProfileEditForm(instance=request.user.profile)
	return render(request, 'account/edit.html', {'user_form': user_form,
												 'profile_form': profile_form})

@login_required
def user_detail(request,username):
	
	user= get_object_or_404(User,username=username)
	shortcomments = ShortComment.objects.filter(author_id=user)
	comments = Comment.objects.filter(author_id=user)
	movies = Movie.objects.filter(users_like=user)
	return render(request,
				'account/user_detail.html',
				{'user':user,
				'shortcomments':shortcomments,
				'comments':comments,
				'movies':movies})

def movie_detail(request, id, slug):
	movie = get_object_or_404(Movie,
							id=id,
							slug=slug)
	r.zincrby('movie_ranking',movie.id,1)
	return 

@login_required
def home(request):
	movies = Movie.objects.all()
	shortcomments = ShortComment.objects.all()
	comments = Comment.objects.all()


	form = SearchForm()
	if 'query' in request.GET:
		form = SearchForm(request.GET)
		if form.is_valid():
			cd = form.cleaned_data
			results = SearchQuerySet().models(Movie).filter(content=cd['query']).load_all()
			# count total results
			total_results = results.count()
		return render(request, 'movies/movie/list.html',
								{'form': form,
								'cd': cd,
								'results': results,
								'total_results': total_results})
	return render(request,
				'account/home.html',
				{'section': 'home',
				'movies':movies,
				'shortcomments':shortcomments,
				'comments':comments})

denv/imovie/account/templates/base.html
{% load staticfiles %}
{% load thumbnail %}
{% load embed_video_tags %}
<!DOCTYPE html>
<html>
	<head>
		<title>{% block title %}{% endblock %}</title>
		<link href="{% static "css/bootstrap.css" %}" rel="stylesheet" type='text/css'>
		<link href="{% static "css/style.css" %}" rel="stylesheet" type='text/css'>
	</head>
	<body>
		{% if messages %}
		<ul class="messages">
			{% for message in messages %}
				<li class="{{ message.tags }}">
					{{ message|safe }}
					<a href="#" class="close">×</a>
				</li>
			{% endfor %}
		</ul>
		{% endif %}

		<div class="container">
			<div class="container_wrap">
				<div class="header_top">
					<div class="col-sm-3 logo"><a href="{% url "home" %}">
						<img src="/media/images/logo.png" alt=""/></a>
					</div>
					<div class="col-sm-6 nav">
					  	<ul>
							<li> <span class="simptip-position-bottom simptip-movable" data-tooltip="review"><a href="{% url "comments:comment_list" %}"> </a></span></li>
							<li><span class="simptip-position-bottom simptip-movable" data-tooltip="movie"><a href="{% url "movies:movie_list" %}"> </a> </span></li>
							<li><span class="simptip-position-bottom simptip-movable" data-tooltip="billborad"><a href="{% url "movies:movie_ranking" %}"> </a></span></li>
							<li><span class="simptip-position-bottom simptip-movable" data-tooltip="activity"><a href="{% url "movies:activity_list" %}"> </a></span></li>
							<li><span class="simptip-position-bottom simptip-movable" data-tooltip="logout"><a href="{% url "login" %}"></a></span></li>
						</ul>
					</div>
					<div class="col-sm-3 header_right" >
						<ul class="header_right_box">
							<li>					
								{% thumbnail request.user.profile.photo "25" as im %}
									<img src="{{ im.url }}" class="img-circle">
								{% endthumbnail %}
							</li>
							<li>
								<p><a href="{% url "dashboard" %}">{{ request.user.username }}</a></p>
							</li>
							<li >
								<span class="simptip-position-bottom simptip-movable" data-tooltip="edit"><a href="{% url "edit" %}"><i class="edit"></a></i>
							</li>
						</ul> 
					</div>			
				<div class="clearfix"> </div>
				</div>

				<div id="content">
					{% block content %}
					{% endblock %}
				</div>
			<div class="clearfix"> </div>
		</div>	
		


		<div class="container"> 
			 <footer id="footer">
				<div id="footer-3d">
					<div class="gp-container">
						<span class="first-widget-bend"></span>
					</div>		
				</div>
				<div id="footer-widgets" class="gp-footer-larger-first-col">
					<div class="gp-container">
						<div class="footer-widget footer-1">
							<div class="wpb_wrapper">
								<img src="/media/images/f_logo.png" alt=""/>
							</div> 
						  <br>
						  <p class="text">Welcome to our lovely website.</p>
						 </div>
						 <div class="footer_box">
						 <div class="col_1_of_3 span_1_of_3">
								<h3>Information</h3>
								<ul class="first">
									<li><a href="{% url "movies:activity_list" %}">Movie Activity</a></li>
									<li><a href="{% url "movies:movie_ranking" %}">Top movie</a></li>
									<li><a href="#">About us</a></li>
								</ul>
						 </div>
						 <div class="col_1_of_3 span_1_of_3">
								<h3>Follow Us</h3>
								<ul class="first">
									<li><a href="#">Facebook</a></li>
									<li><a href="#">Twitter</a></li>
									<li><a href="#">Youtube</a></li>
								</ul>
						 </div>
						<div class="clearfix"> </div>
						</div>
						<div class="clearfix"> </div>
					</div>
				</div>
			</footer>
		</div>		

			<script src="/static/js/jquery-2.1.4.min.js"></script>
			<script src="/static/js/jquery-1.4.1.cookie.min.js "></script>
			<script src="/static/js/responsiveslides.min.js"></script>

			<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
			<script>
				var csrftoken = $.cookie('csrftoken');
				function csrfSafeMethod(method) {
					// these HTTP methods do not require CSRF protection
					return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
				}
				$.ajaxSetup({
					beforeSend: function(xhr, settings) {
						if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
							xhr.setRequestHeader("X-CSRFToken", csrftoken);
						}
					}
				});

				$(document).ready(function(){
					{% block domready %}
					{% endblock %}
				});
			</script>
	</body>
</html>